/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Menu;
//import HiloReloj.RelojLabel;
import BarraCarga.BarraCarga;
import Reloj.RelojLabel;
/**
 *
 * @author David Alejandro Tirado Luna 00000233047
 */
public class Principal extends javax.swing.JFrame {


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        new RelojLabel(lblReloj); // <- Aquí se inicia el reloj
        new BarraCarga();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblReloj = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        pacientesMenu = new javax.swing.JMenu();
        agregarNuevoPacienteMenuItem = new javax.swing.JMenuItem();
        eliminaPacienteMenuItem = new javax.swing.JMenuItem();
        consultarPacienteMenuItem = new javax.swing.JMenuItem();
        actualizarPacienteMenuItem = new javax.swing.JMenuItem();
        medicosMenu = new javax.swing.JMenu();
        agregarNuevoMedicoMenuItem = new javax.swing.JMenuItem();
        consultarMedicoMenuItem = new javax.swing.JMenuItem();
        equipoMedMenu = new javax.swing.JMenu();
        consultarInventarioMenuItem = new javax.swing.JMenuItem();
        inventariarMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        agendaConsultaMenuItem = new javax.swing.JMenuItem();
        cancelaConsultaMenuItem = new javax.swing.JMenuItem();
        BuscaConsultaenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReloj.setText("Reloj");

        pacientesMenu.setMnemonic('f');
        pacientesMenu.setText("Pacientes");
        pacientesMenu.setToolTipText("");

        agregarNuevoPacienteMenuItem.setMnemonic('o');
        agregarNuevoPacienteMenuItem.setText("Agregar Nuevo");
        agregarNuevoPacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNuevoPacienteMenuItemActionPerformed(evt);
            }
        });
        pacientesMenu.add(agregarNuevoPacienteMenuItem);

        eliminaPacienteMenuItem.setMnemonic('x');
        eliminaPacienteMenuItem.setText("Eliminar");
        eliminaPacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaPacienteMenuItemActionPerformed(evt);
            }
        });
        pacientesMenu.add(eliminaPacienteMenuItem);

        consultarPacienteMenuItem.setMnemonic('s');
        consultarPacienteMenuItem.setText("Consultar ");
        consultarPacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPacienteMenuItemActionPerformed(evt);
            }
        });
        pacientesMenu.add(consultarPacienteMenuItem);

        actualizarPacienteMenuItem.setMnemonic('a');
        actualizarPacienteMenuItem.setText("Actualizar información");
        actualizarPacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPacienteMenuItemActionPerformed(evt);
            }
        });
        pacientesMenu.add(actualizarPacienteMenuItem);

        menuBar.add(pacientesMenu);

        medicosMenu.setMnemonic('e');
        medicosMenu.setText("Medicos");

        agregarNuevoMedicoMenuItem.setMnemonic('t');
        agregarNuevoMedicoMenuItem.setText("Agregar Nuevo");
        agregarNuevoMedicoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNuevoMedicoMenuItemActionPerformed(evt);
            }
        });
        medicosMenu.add(agregarNuevoMedicoMenuItem);

        consultarMedicoMenuItem.setMnemonic('y');
        consultarMedicoMenuItem.setText("Consultar");
        consultarMedicoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMedicoMenuItemActionPerformed(evt);
            }
        });
        medicosMenu.add(consultarMedicoMenuItem);

        menuBar.add(medicosMenu);

        equipoMedMenu.setMnemonic('h');
        equipoMedMenu.setText("Equipo Médico");

        consultarInventarioMenuItem.setMnemonic('c');
        consultarInventarioMenuItem.setText("Consultar Inventario");
        consultarInventarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarInventarioMenuItemActionPerformed(evt);
            }
        });
        equipoMedMenu.add(consultarInventarioMenuItem);

        inventariarMenuItem.setMnemonic('a');
        inventariarMenuItem.setText("Inventariar");
        inventariarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventariarMenuItemActionPerformed(evt);
            }
        });
        equipoMedMenu.add(inventariarMenuItem);

        jMenuItem2.setText("Desinventariar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        equipoMedMenu.add(jMenuItem2);

        menuBar.add(equipoMedMenu);

        consultasMenu.setText("Consultas Médicas");

        agendaConsultaMenuItem.setText("Agendar nueva consulta");
        agendaConsultaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaConsultaMenuItemActionPerformed(evt);
            }
        });
        consultasMenu.add(agendaConsultaMenuItem);

        cancelaConsultaMenuItem.setText("Cancelar consulta programada");
        cancelaConsultaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaConsultaMenuItemActionPerformed(evt);
            }
        });
        consultasMenu.add(cancelaConsultaMenuItem);

        BuscaConsultaenuItem.setText("Buscar consulta");
        BuscaConsultaenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaConsultaenuItemActionPerformed(evt);
            }
        });
        consultasMenu.add(BuscaConsultaenuItem);

        menuBar.add(consultasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminaPacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaPacienteMenuItemActionPerformed
        FormEliminaPaciente newFrame = new FormEliminaPaciente();
        newFrame.setVisible(true);


    }//GEN-LAST:event_eliminaPacienteMenuItemActionPerformed

    private void agregarNuevoPacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNuevoPacienteMenuItemActionPerformed

        FormRegistroPaciente newFrame = new FormRegistroPaciente(this);
        newFrame.setVisible(true);
    }//GEN-LAST:event_agregarNuevoPacienteMenuItemActionPerformed

    private void inventariarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventariarMenuItemActionPerformed
        FromInventariar newFrame = new FromInventariar();
        newFrame.setVisible(true);
    }//GEN-LAST:event_inventariarMenuItemActionPerformed

    private void consultarPacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPacienteMenuItemActionPerformed
        FormConsultaPaciente newFrame = new FormConsultaPaciente();
        newFrame.setVisible(true);


    }//GEN-LAST:event_consultarPacienteMenuItemActionPerformed

    private void agregarNuevoMedicoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNuevoMedicoMenuItemActionPerformed
        FormRegisgtroMedico newFrame = new FormRegisgtroMedico();
        newFrame.setVisible(true);


    }//GEN-LAST:event_agregarNuevoMedicoMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormDesinventariar newFrame = new FormDesinventariar();
        newFrame.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void actualizarPacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPacienteMenuItemActionPerformed
        FormEdicionPaciente newFrame = new FormEdicionPaciente();
        newFrame.setVisible(true);


    }//GEN-LAST:event_actualizarPacienteMenuItemActionPerformed

    private void consultarMedicoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMedicoMenuItemActionPerformed
        FormConsultaMedico newFrame = new FormConsultaMedico();
        newFrame.setVisible(true);

    }//GEN-LAST:event_consultarMedicoMenuItemActionPerformed

    private void consultarInventarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarInventarioMenuItemActionPerformed
        FormConsultaInventario newFrame = new FormConsultaInventario();
        newFrame.setVisible(true);

    }//GEN-LAST:event_consultarInventarioMenuItemActionPerformed

    private void agendaConsultaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaConsultaMenuItemActionPerformed
        FormGenerarConsulta newFrame = new FormGenerarConsulta();
        newFrame.setVisible(true);
    }//GEN-LAST:event_agendaConsultaMenuItemActionPerformed

    private void cancelaConsultaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaConsultaMenuItemActionPerformed
        FormEliminarConsulta newFrame = new FormEliminarConsulta();
        newFrame.setVisible(true);

    }//GEN-LAST:event_cancelaConsultaMenuItemActionPerformed

    private void BuscaConsultaenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaConsultaenuItemActionPerformed
        FormBuscaConsulta newFrame = new FormBuscaConsulta();
        newFrame.setVisible(true);

    }//GEN-LAST:event_BuscaConsultaenuItemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuscaConsultaenuItem;
    private javax.swing.JMenuItem actualizarPacienteMenuItem;
    private javax.swing.JMenuItem agendaConsultaMenuItem;
    private javax.swing.JMenuItem agregarNuevoMedicoMenuItem;
    private javax.swing.JMenuItem agregarNuevoPacienteMenuItem;
    private javax.swing.JMenuItem cancelaConsultaMenuItem;
    private javax.swing.JMenuItem consultarInventarioMenuItem;
    private javax.swing.JMenuItem consultarMedicoMenuItem;
    private javax.swing.JMenuItem consultarPacienteMenuItem;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminaPacienteMenuItem;
    private javax.swing.JMenu equipoMedMenu;
    private javax.swing.JMenuItem inventariarMenuItem;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JMenu medicosMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pacientesMenu;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
